config/routes.rb
Rails.application.routes.draw do
  root to: 'jobs#index'

  resources :jobs, only: [:index, :show]
  resources :regions, only: [:index, :show]
  resources :cities, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :jobs
  has_many :city_regions
  has_many :regions, through: :city_regions

  validates_presence_of :name
end

app/models/city_region.rb
class CityRegion < ApplicationRecord
  belongs_to :city
  belongs_to :region
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  belongs_to :city

  validates_presence_of :title, :base_salary, :company

  YES_NO_UNKNOWN = [:no, :yes, :unknown].freeze

  validates :has_nearterm_perf_review, presence: true, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 2
  }
  validates :has_bonus, presence: true, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 2
  }
  validates :has_equity, presence: true, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 2
  }
  validates :has_medical, presence: true, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 2
  }
  validates :has_dental, presence: true, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 2
  }
  validates :has_vision, presence: true, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 2
  }
  validates :has_wfh, presence: true, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 2
  }
  validates :has_family_leave, presence: true, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 2
  }
  validates :has_retirement, presence: true, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 2
  }
  validates :has_prof_devel, presence: true, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 2
  }
  validates :hardware_provided, presence: true, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 2
  }

end

app/models/region.rb
class Region < ApplicationRecord
  has_many :city_regions
  has_many :cities, through: :city_regions
end

app/models/user.rb
class User < ApplicationRecord
  has_many :jobs
  has_many :cities, through: :jobs

  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates_presence_of :name

  enum role: [:student, :admin]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.order(created_at: :desc)
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cities/index.html.erb
<h1>Cities#index</h1>
<p>Find me in app/views/cities/index.html.erb</p>

app/views/cities/show.html.erb
<h1>Cities#show</h1>
<p>Find me in app/views/cities/show.html.erb</p>

app/views/jobs/create.html.erb
<h1>Jobs#create</h1>
<p>Find me in app/views/jobs/create.html.erb</p>

app/views/jobs/edit.html.erb
<h1>Jobs#edit</h1>
<p>Find me in app/views/jobs/edit.html.erb</p>

app/views/jobs/index.html.erb
jobs go here
<ul>
<% @jobs.each do |job| %>
  <li id="#job-<%= job.id %>"><%= link_to job.title, job_path(job) %></li>
<% end %>
</ul>

app/views/jobs/new.html.erb
<h1>Jobs#new</h1>
<p>Find me in app/views/jobs/new.html.erb</p>

app/views/jobs/update.html.erb
<h1>Jobs#update</h1>
<p>Find me in app/views/jobs/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Salaries</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag href= 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
  </head>

  <body class="fixed skin-blue-light">
  <div class="wrapper">
    <%= render 'layouts/navigation/layout'%>
    <div class="content-wrapper">
      <%= yield %>
    </div>
    <%= render 'layouts/navigation/footer' %>
  </div>
  </body>
</html>

app/views/layouts/navigation/_footer.html.erb
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    Anything you want
  </div>
  <strong>
    Copyright © 2018
    <a href="https://turing.io"> Turing School of Software &amp; Design</a>
  </strong>
  All rights reserved.
</footer>

app/views/layouts/navigation/_header.html.erb
<header class="main-header">
  <a class="logo" href="/">Turing Salaries</a>

  <nav class="navbar navbar-static-top" role="navigation">
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li class="user user-menu"><a>Post and manage your salary information</a></li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/navigation/_layout.html.erb
<%= render 'layouts/navigation/header' %>
<%= render 'layouts/navigation/sidebar/main' %>

app/views/layouts/navigation/sidebar/_main.html.erb
<div class="main-sidebar">
  <div class="sidebar">
    <%#= render 'layouts/navigation/sidebar/user' %>
    <%#= render 'layouts/navigation/sidebar/search' %>
    <ul class="sidebar-menu">
      <li class="header">
        HEADER
      </li>
      <li class="active">
        <a href="#">
          <span>Link</span>
        </a>
      </li>
      <li>
        <a href="#">
          <span>Another Link</span>
        </a>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/navigation/sidebar/_search.html.erb
<form action="#" class="sidebar-form" method="get">
  <div class="input-group">
    <input class="form-control" name="q" placeholder="Search..." type="text" />
    <span class="input-group-btn">
        <button class="btn btn-flat" id="search-btn" name="search" type="submit">
        <i class="fa fa-search">
        </i></button></span>
  </div>
</form>

app/views/layouts/navigation/sidebar/_user.html.erb
<div class="user-panel">
  <div class="pull-left image">
    <img alt="User Image" class="user-image" src="http://placehold.it/160x160" />
  </div>
  <div class="pull-left info">
    <p>
      User Name
    </p>
    <a href="#">
      <i class="fa fa-circle text-success">
      </i>Online
    </a>
  </div>
</div>

app/views/regions/index.html.erb
<h1Regions and Their Cities</h1>
<p>Find me in app/views/regions/index.html.erb</p>

app/views/regions/show.html.erb
<h1>Regions#show</h1>
<p>Find me in app/views/regions/show.html.erb</p>